### ISSUE TITLE
Translation artifacts

### ISSUE THREAD

**Issue by loshhilov** [jumpinjackie/mapguide-react-layout#1007]
When using a locale other than English, values of the lines "INIT", "INIT_DESC" and "LOADING_MSG" are always accepted from the en.ts file.
These values from /viewer/strings/<other_locale >.json are ignored.
Do you need them at all if there 's an indicator?

**Comment by jumpinjackie** [comment]
The issue is that we set the locale after we've init'ed everything in the viewer. We can actually set the locale earlier than that (straight after the non-en bundle has been fetched and registered). I'll make a fix so that viewer init sets the locale earlier, meaning you should see the loading text in your locale (although the viewer loading text will still momentarily be in english until the strings are fetched and registered)
