### ISSUE TITLE
mapguide is requested with wrong scale when windows scale not set to 100%

### ISSUE THREAD

**Issue by vitjok** [jumpinjackie/mapguide-react-layout#1011]
## Expected behavior

In Sheboygan sample there is a Buildings layer which is visible in scale range 0:1500.

Using mapguide-react-layout with resource Library://Samples/Sheboygan/FlexibleLayouts/React.ApplicationDefinition and scale 1128 the buildings are visible in map and also in legend (as expected):

![image](https://user-images.githubusercontent.com/3989972/69146742-c1da3580-0ad0-11ea-8b6b-f6f2fd1bded1.png)

And **both** are invisible at scale 1594 (as expected):

![image](https://user-images.githubusercontent.com/3989972/69147207-bd624c80-0ad1-11ea-9916-da2ca899933e.png)

## Unexpected behavior

But when I move the window to an screen where I set the scaling to **150% in window**s, then the buildings are visible at scale 1594 in the map and are invisible in the legend (unexpected):

![image](https://user-images.githubusercontent.com/3989972/69147410-24800100-0ad2-11ea-88ed-5463279efa59.png)

I took a look to the requested URLs.

On the 100% scaled screen, mapguide is requested with scale 1594.9490556911599 (which is not exactly the same as as stated in gui (1594.9458657930481), but I think it is sufficient):

```
http://localhost/mapguide/mapagent/mapagent.fcgi?OPERATION=GETDYNAMICMAPOVERLAYIMAGE&VERSION=2.0.0&LOCALE=en&CLIENTAGENT=ol.source.ImageMapGuide%20source&CLIP=1&SETDISPLAYDPI=96&SETDISPLAYWIDTH=133&SETDISPLAYHEIGHT=375&SETVIEWSCALE=1594.9490556911599&SETVIEWCENTERX=-87.72871993108795&SETVIEWCENTERY=43.75518690231107&MAPNAME=MainMap&FORMAT=PNG&SESSION=6b9326e8-0ac4-11ea-8000-8c16454ad52b_en_MTI3LjAuMC4x0AFC0AFB0AFA&BEHAVIOR=2&showlayers=&showgroups=&hidelayers=&hidegroups=
```

On the 150% scaled screen, mapguide is requested with scale 1063.2993704607734:

```
http://localhost/mapguide/mapagent/mapagent.fcgi?OPERATION=GETDYNAMICMAPOVERLAYIMAGE&VERSION=2.0.0&LOCALE=en&CLIENTAGENT=ol.source.ImageMapGuide%20source&CLIP=1&SETDISPLAYDPI=96&SETDISPLAYWIDTH=199&SETDISPLAYHEIGHT=564&SETVIEWSCALE=1063.2993704607734&SETVIEWCENTERX=-87.72872245832994&SETVIEWCENTERY=43.75518690231107&MAPNAME=MainMap&FORMAT=PNG&SESSION=6b9326e8-0ac4-11ea-8000-8c16454ad52b_en_MTI3LjAuMC4x0AFC0AFB0AFA&BEHAVIOR=2&showlayers=&showgroups=&hidelayers=&hidegroups=
```

**Comment by jumpinjackie** [comment]
For purpose of reproducing this, how do you change windows scaling on Windows 10 (I assume this is the OS your screenshots are from) ?

**Comment by vitjok** [comment]
> [...] how do you change windows scaling [...]?

I change it in this dialog:

![image](https://user-images.githubusercontent.com/3989972/69341031-0bf61f00-0c69-11ea-8727-36167b904420.png)

Actually I can reproduce the behavior by scale the page in Chrome when the windows setting still on 100%:

![ScreenCapture_21 11 2019 14 14 32](https://user-images.githubusercontent.com/3989972/69341434-dd2c7880-0c69-11ea-83c9-84c09f673a51.gif)

The two different reproducing ways lead to the same behavior, but I don't know whether it is really "the same".

**Comment by jumpinjackie** [comment]
An update on this. I've identified the problem. It's because of 2 things:

 * OpenLayers is driven by bounding boxes. This bounding box is the source of truth to what the current view is.
 * Our viewer is driven by x/y/scale. Thus, what the viewer reports is ultimately derived from conversions from bounding boxes, and whenever we want to go to a x/y/scale, whatever we set ultimately translates to a bounding box.

The problem here is that OpenLayers's bounding box calculations factor the `window.devicePixelRatio` which I am suspecting that our scale to resolution conversion code is not factoring in. On original scaling this value is 1, on >100% zoom, this value will be greater than 1 and this is throwing off whatever calculations/conversions we're doing.

Still investigating what the solution is.
