### ISSUE TITLE
Allow custom cursors to be disabled (was: React Viewer middle mouse scroll button (DragPan) icon stays selected)

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/mapguide-react-layout#1447]
Originally posted here: https://github.com/jumpinjackie/mapguide-maestro/issues/135

**When clicking the middle mouse scroll button (DragPan) it changes to a 'circle with arrows in it' icon, and this will let you pan on the map. However, after doing this doesn't matter what other icons (functions) you click on, on the React Viewer toolbar, or right-clicking on the map it doesn't change the icon back to the selected toolbar function. The functions seem to be selected and working but the icons stay as is.
**

Issue reproduced on the following browsers:
Microsoft Edge, and Google Chrome

MapGuide 4.0.0 Preview 4

MapGuide Maestro Release 6.0m11 (6.0.0.473)

**Comment by jumpinjackie** [comment]
I cannot reproduce

**Comment by Jackson-Percy** [comment]
Hi Jackie, Please find here https://web.microsoftstream.com/video/02e182de-e681-48bb-9cc4-60f7b15edf26 a video of what happens when I do the same thing, click the wheel on the mouse and hold in, and it works like pan function. However, as you can see the icon does not change back when clicking the Select icon on the toolbar or the Pan icon on the toolbar. The functions still work just the icon does not revert back. As stated it only happens on Chromium browsers (Chrome and Edge) but NOT on Firefox.

**Comment by jumpinjackie** [comment]
That link requires a Microsoft login. Can you just attach a zip of the video here?

**Comment by jumpinjackie** [comment]
Ok having seen a demo of this issue, I speculate that this is happening as a result of trying to change the mouse cursor. I'll look at a viewer option to disable cursor changing on select/pan/zoom/etc.

Failing that, there is a demonstrable workaround of just double-middle-click again to restore back to the default cursor.
