### ISSUE TITLE
Extra custom icons

### ISSUE THREAD

**Issue by VolkerDr** [jumpinjackie/mapguide-react-layout#1477]
The extraLayerIconsHtml / extrGroupIconsHtml is very nice.
What do you think about declaration in the layerdefinition ExtendedData section?
Regards Volker

**Comment by jumpinjackie** [comment]
Sorry, I don't like that. Because viewer init does not fetch layer definitions.

Having this information in layer definition ExtendedData would mean that we have to fetch each individual layer definition to get at it data, and that just scales extremely poorly with the size of the map you are viewing.
