### ISSUE TITLE
Unable to display downloaded KML on google Earth

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#203]
Hello Jackie:
Is there any function where I can change the Line Color of KML which is downloaded from Redline.
As of now, i am getting black color ( 000000 ) with thickness 0.00010 under style id=0.

For your reference, please find the attached downloaded KML. 
( I have attached it as a text file which is actually a KML file. ).

<Style id="0">
<LineStyle><color>00000000</color><width>0.000010</width></LineStyle>
<PolyStyle><color>FF00FF00</color></PolyStyle>
</Style>

Unable to display the KML in google earth with parameters mentioned in style id = 0.

When I change the Parameters manually as below, in downloaded KML file, the redline is displaying on google earth

<Style id="0">
<LineStyle><color>FF00FF00</color><width>1.000010</width></LineStyle>
<PolyStyle><color>FF00FF00</color></PolyStyle>
</Style>

[RedlineLayer.txt](https://github.com/jumpinjackie/mapguide-react-layout/files/946863/RedlineLayer.txt)

**Comment by jumpinjackie** [comment]
This is a MapGuide-level problem that has been fixed for a long time (since 2.6)

https://trac.osgeo.org/mapguide/ticket/2485

Based on your previous query (#196), I don't think your version of AIMS has this fix. I can't do much about that.

The only practical workaround I can see for you would be to edit these lines:

https://github.com/jumpinjackie/mapguide-react-layout/blob/master/viewer/server/Redline/classes/markupmanager.php#L598

and

https://github.com/jumpinjackie/mapguide-react-layout/blob/master/viewer/server/Redline/classes/markupmanager.php#L614

To ensure a [value >= 1.0] is passed in

**Comment by saivaradula** [comment]
Jackie:
Thank you for the info.
Issue is resolved. 

- Sai
