### ISSUE TITLE
Supporting Widgets that use InvokeScript 

### ISSUE THREAD

**Issue by a1astair** [jumpinjackie/mapguide-react-layout#247]
It looks like based on issue [#14](https://github.com/jumpinjackie/mapguide-react-layout/issues/14) there is a replacement story InvokeScript commands and I was wondering if you could elaborate on that.

If you could let me know the steps in order to get widgets that use InvokeScript for custom functionality, or at least point me in the right direction as to how I could get that to work, I would greatly appreciate it.

Also what would be the proper direction to take in order to add in custom functionality or custom widgets into the layout.

**Comment by jumpinjackie** [comment]
The replacement for InvokeScript commands is registered script commands. The idea behind this is that instead of baking in arbitrary JS code into WebLayouts and ApplicationDefinitions, you bake such code into script commands in your own custom viewer bundle, and the existing InvokeScript definitions in your WebLayout/ApplicationDefinition become merely references so the viewer knows what command to invoke.

To make use of registered script commands, you need to use the mapguide-react-layout npm module.

You should have a look at my [this example here](https://github.com/jumpinjackie/mapguide-react-layout-example) that demonstrates how to use:

 * Registered script commands
 * Custom viewer templates
 * Custom viewer components

Hope that helps.

**Comment by a1astair** [comment]
Thanks for the quick response, I was also wondering, what is the best way to ask questions about this new layout. Is it to create issues?

**Comment by jumpinjackie** [comment]
Yep, feel free to make make issues for any questions you may have. Just make sure to tag it with the `question` label. Or if you're not able to do that, I'll tag it when I come round to seeing the issue.

**Comment by a1astair** [comment]
Perfect thanks so much!
