### ISSUE TITLE
Quick Plot Preview Remains After Plot Complete

### ISSUE THREAD

**Issue by Crispin-at-Linknode** [jumpinjackie/mapguide-react-layout#310]
When I use the quick plot (viewer, not Fusion) with the advanced options the map screen has a plot overlay to indicate the scale and rotation of the plot.

After completing the plot, this extents preview overlay remains on the map with no indication as to how to remove it (bar dragging off screen).

Chrome 60, Sheboygan Data
http://localhost/mapguide31/viewer/sidebar.html?resource=Library://Samples/Sheboygan/Layouts/SheboyganAspTiled.WebLayout

**Comment by jumpinjackie** [comment]
Hmmm, if you're referring to the current revision on master, it's not quite complete yet. 

I've yet to figure out the right set of parameters to send to PlotAsPDF.php so it will properly plot a rotated map.

But focusing on the problem at hand, the box currently goes away when you un-tick the advanced options checkbox. 

It should also be going away if the QuickPlot component unmounts (due to opening something else in the Task Pane, if it's docked there or through closing its parent modal if it's housed in a modal dialog). This bit I haven't done yet.

**Comment by Crispin-at-Linknode** [comment]
OK, I'll try and note to untick advanced before closing the box.  I hadn't realised it was Work in Progress -- disappearing on unmounting / close on plot complete will be ideal.

My rotated maps looked OK, apart from the possibility of filling-in the map to fill the plot space when rotated, but I wasn't looking at output carefully yet

**Comment by jumpinjackie** [comment]
The joys of playing with bleeding edge code on master. Things may break or be not quite complete :)

The actual tracking issue (to finish porting the whole widget) is #188 

I'll leave this open to address the "remove capture box layer on unmount" aspect of the component.
