### ISSUE TITLE
Option to make selection panel active when selection is made

### ISSUE THREAD

**Issue by Rastamafugg** [jumpinjackie/mapguide-react-layout#341]
Is there a way to automatically make the selection panel active when a user makes a selection?  I don't see any redux actions occurring when I manually toggle the selection panel, either, so perhaps this is not possible with the current release?

**Comment by jumpinjackie** [comment]
None of the built-in layout templates handle the `MAP_SET_SELECTION` action in their template reducer functions, which means none of the templates make the selection panel active or appear when a selection is made.

I'm hesitant to bake this behavior into the existing layout templates because some applications may care about responding to selections from task pane content and updating some part of the task pane content. Auto-activating the selection panel in some templates would mess that up.

If you're making your own layout template, just make sure your custom template reducer function is handling `MAP_SET_SELECTION` and if the payload has selected features then return a new state with selection panel visibility set to `true`, which the layout template will know to then present the selection panel.
