### ISSUE TITLE
Bing / Google Maps as basemaps

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#386]
Hello Jackie:
We are using AIMS 2017 Server & Studio.  ( Autodesk has not confirmed 2018 release yet ).  As per our client, we need to display Satellite or street maps as a base map using Bing or Google. 
Kindly help us to configure google maps key or Bing Maps key so that we can display satellite/street maps from Google or Bing.

- Sai

**Comment by jumpinjackie** [comment]
The react viewer does not support Google Maps. I have no intention of adding Google Maps support if OpenLayers itself does not support it. So I'll only describe the support for Bing Maps.

Make sure to grab and install the latest [6.0m7 release](https://github.com/jumpinjackie/mapguide-maestro/releases/tag/6.0m7) of MapGuide Maestro.

Open the Application Definition document you are feeding into the react viewer.

In the map's section and any of the available Bing Maps layers and make sure you set the Bing Maps API Key as indicated in this screenshot below and click **Set API Key** to record it into the Application Definition document.

![bingmapsapi](https://user-images.githubusercontent.com/563860/31554901-d098b922-b08a-11e7-9fd1-083ffac28b33.png)

**Comment by saivaradula** [comment]
Jackie:
We are using Oracle 11g Database. MapGuide Mastro FDO Provider isn't supporting oracle 11g. 
if you can, please provide Oracle 11g FDO provider and process to work with Matro.

- Sai

**Comment by jumpinjackie** [comment]
When I wrote this blog post (https://themapguyde.blogspot.com.au/2016/12/my-oracle-xe-setup-adventure-with-docker.html), I was connecting to an Oracle 11g instance using the `King.Oracle` FDO provider that is included with MapGuide

If Oracle support is not working, it's because either the `King.Oracle` or `Autodesk.Oracle` FDO provider is not installed, or it is installed (it's on the list of FDO providers when you create a Feature Source and are prompted to choose it) but it cannot find `OCI.dll` from your Oracle Client installation.

**Comment by saivaradula** [comment]
Thanks for the information. This has been resolved. 

- Sai

**Comment by satregiftc** [comment]
HI..

i am not able to connect to Oracle from Map guide studio 2017 , My Database is Oracle 12c (64 Bit ) and Clinet is 12 c (64 bit)  , when i tried to connect oracle from studio i am getting Oci.dll not for exception, checked environmental variables, everything looks fine. can you help us to solve this issue.

Thanks 
SAtish
