### ISSUE TITLE
Point not visible in Redline.

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#412]
Hello Jackie:

I am not able to draw POINT using the redline task pane and the point is not visible on Map after redline markup. 
I am able to draw the Polygon using redline and save it as KML,  but not the point. 

- Sai

**Comment by jumpinjackie** [comment]
Demo link?

**Comment by jumpinjackie** [comment]
Thanks for the demo link. I think I see the problem.

You are storing your redlines in a SHP feature source. However SHP files can only store geometries **of one geometry type**. Nothing is happening with points because you sent a request to `newmarkup.php` with geometry type of 4 (Polygons).

Does this work if you choose `OSGeo.SDF` or `OSGeo.SQLite` with geometry type of 5 (1|4, 1=Point,4=Polygon) ?

**Comment by saivaradula** [comment]
Jackie:

I tried with both OSGeo.SDF and OSGeo.SQLite, but the result is same, it did not capture the point on the map.

Please digitize point using URL below in which OSGeo.SDF is markup provider.

URL:
http://183.83.218.176/REGEN/viewer/aqua.html?resource=Library%3a%2f%2fREGEN%2fLAYOUT%2fREGEN3.ApplicationDefinition

Click on the 5th Icon in the horizontal icon list.

Please suggest if I need to make any other changes to make point work in Redline. 

- Sai

**Comment by jumpinjackie** [comment]
You have to modify your `newmarkup.php` request to also set `MARKUPGEOMTYPE` to `5` (which is 1 | 4, 1 = Point, 4 = Polygon)

**Comment by saivaradula** [comment]
Thank you for the help and worked.

- Sai
