### ISSUE TITLE
Draw a Line in Measure widget

### ISSUE THREAD

**Issue by saivaradula** [jumpinjackie/mapguide-react-layout#413]
Hello Jackie:

I am not able to use the line functionality in Measure widget. Polygon is working fine, but I am not able use Line. 

I am using version 0.10 

Thanks alot in advance.

- Sai

**Comment by jumpinjackie** [comment]
I think something in your CSS is causing the tracking tooltip (that's showing the measurement) to not be "far away" enough from the mouse pointer. Meaning when I try to double-click, it's actually trying to interact with the tracking tooltip content (and selecting the text) instead of interacting with the map.

![2017-10-31 21_46_38-regen3](https://user-images.githubusercontent.com/563860/32220240-1ef56662-be85-11e7-870c-04bdc182c461.png)

The tracking tooltip content should not be that close to the mouse pointer.

**Comment by saivaradula** [comment]
Thanks for pointing out Jackie.
It was great help.

- Sai
