### ISSUE TITLE
Oracle 12c connection from Map guide 2017

### ISSUE THREAD

**Issue by satregiftc** [jumpinjackie/mapguide-react-layout#458]
Hi Jackie

i am not able to connect to Oracle from Map guide studio 2017 , My Database is Oracle 12c (64 Bit ) and Clinet is 12 c (64 bit) , when i tried to connect oracle from studio i am getting Oci.dll not found exception error
From Autodesk 3d map 2017 , Oracle FDO connectivity is working fine , checked environmental variables, everything looks fine. can you help us to solve this issue.

Thanks
SAT

**Comment by jumpinjackie** [comment]
This issue is not related to this project at all (you should've posted to mapguide-users or fdo-users mailing list)

But I'll answer anyways: 

The King Oracle FDO provider is built against the Oracle **11g** instant client. Can an 11g client connect to a 12c database? I do not know, but this is the facts of the matter. 

Since the FDO provider expects an 11g OCI.dll, I don't think you can just drop a 12c OCI.dll in its place.
