### ISSUE TITLE
Populating tooltip on Mouse click

### ISSUE THREAD

**Issue by karunainfotech** [jumpinjackie/mapguide-react-layout#475]
Hello Jackie:

I am using viewer for the displaying the maps with polygons with Mapguide ( AIIMS ). I have a tooltip which populates on moving mouse onto the polygons ( on mouseover ),  can I change this to mouse click on to the polygon ( on mouse click ). 

Please suggest me.

- KK.

**Comment by jumpinjackie** [comment]
The only question here is that this will interfere with feature selection. You click on a map do you want to:

 * Try and select whatever you just clicked?
 * Show the tooltip?
 * Both?

**Comment by karunainfotech** [comment]
Both will be good, if it is taking more time for implementation of both the functionalities, Showing the tooltip is what I suggest to be priority.

- KK

**Comment by karunainfotech** [comment]
Hello Jackie:
If there are any changes to the above enhancement, please let me know so that I can download or change the code.

- KK

**Comment by jumpinjackie** [comment]
When I release 0.11 (sometime this month), you can enable manual feature tooltips through a new mount option `manualFeatureTooltips`:

```
viewer.mount(el, {
    ...
    initialConfig: {
        manualFeatureTooltips: true //This will enable manual feature tooltips
    }
});
```

In manual feature tooltips mode, if the feature tooltips component is toggled on, map clicks will trigger a tooltip query (and present the tooltip) instead of doing a map selection at that point. In this mode, you can still do map selections via:

 * Dragging a selection box while the Select tool is active
 * Select Radius
 * Select Polygon

In manual feature tooltips mode, if the feature tooltips component is toggled off, then clicks on the map will do map selections as normal.
