### ISSUE TITLE
Slow Rendering of the map 

### ISSUE THREAD

**Issue by karunainfotech** [jumpinjackie/mapguide-react-layout#485]
[serverconfig.ini.txt](https://github.com/jumpinjackie/mapguide-react-layout/files/1615068/serverconfig.ini.txt)

Hello Jackie:

I have loaded MapGuide react layout with the following environment.

Windows Server 2012 R2
IIS 7
Oracle 12c
AIMS 2017.

When I load the map in react ( viewer ),
the background map refreshes fast but vector map rendering is very slow. 

Pls find below URL:

http://103.203.138.154/REGEN/viewer/aqua.html?resource=Library%3a%2f%2fREGEN%2fLAYOUT%2fREGEN3.ApplicationDefinition&action=zoom&LAYERNAME=RIICO_IA_BOUNDARY&KEYNAME=FeatId&KEYVALUE=217362&ISSTRING=false&SECONDKEYNAME=IA_NAME&SECONDKEYVALUE=BAP&CLEAR=1&type=nl&x=72.3796609616191&y=27.3801697290446

The load indicator moves quite fast till about 80% and slows down for the remaining 20% when I perform map zoom-in and map zoom-out.

Please find attached server config.ini file, kindly suggest how we can identify bottlenecks in performance and suggest ways to improve MapGuide react performance. 

- KK

**Comment by jumpinjackie** [comment]
The load indicator is not a true indicator of loading progress. It is something that is merely shown so that you know the viewer is waiting on a rendering result. It just animates at an exponentially slower speed the longer the rendering operation takes.

You should profile your map using the profiling tool in the Site Administrator to get a better idea of which layers are bottlenecking performance.
