### ISSUE TITLE
Unrealistic upper-bound scale on Navigator

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/mapguide-react-layout#86]
For untiled maps the upper-bound scale on the Navigator is excessively high

For tiled maps, the scales will correctly "snap" to the finite scale list, but the slider position at the highest scale is still in the middle, whereas it is at the bottom for both AJAX/Fusion viewers.

**Comment by Crispin-at-Linknode** [comment]
The snapping is a big improvement for tiled maps (#84).
However even when setting all layers within a Sheboygan test map set to having a maximum display scale of 1:30,000 there still seems to be something that lets the slider go to near infinity so that the relative positions of the snapping layer scales are still impractically at the top end of the slider

**Comment by Crispin-at-Linknode** [comment]
I looked at the slider code in "navigator.tsx" and the log and pow stuff really confused me - why is there a log scale in there?  The original AJAX viewer has slider code around line 1560 of ajaxmappane.templ that I could understand.

In order to try and fix the Tiled Map slider there seems to be the possibility of some mass simplification.  My code is horrid and not 100% right, but this seems a simpler approach for "calculatePosForScale" and "calculateScaleForPos" for tiled maps:

    private calculatePosForScale(scale: number): number {
        var pos = 1;
        if (this.finiteScaleList) {
            var iFiniteScale = 1;
            for (let i = 0; i < this.finiteScaleList.length; i++) {
                if (scale >= this.finiteScaleList[i]) { //Found the lower bound
                    if (scale <= this.finiteScaleList[i +1]) { //It is the upper bound
                        iFiniteScale = i;
                    }
                }
            }            
            pos = VERT_START + (iFiniteScale * ((VERT_SPAN - VERT_START) / this.finiteScaleList.length));
        } else {
            pos = 9 * Math.log(scale) / LN9;
        }
        return Math.floor(pos);
    }
    private calculateScaleForPos(pos: number): number {
        const scale = Math.pow(9,pos/9.0);

        if (this.finiteScaleList) {
            const iFiniteScale = Math.floor((pos - VERT_START) / ((VERT_SPAN - VERT_START) / this.finiteScaleList.length));

           return this.finiteScaleList[iFiniteScale];

**Comment by jumpinjackie** [comment]
FYI, my original code "template" was the Fusion Navigator (ZoomSlider) widget. That's where all the log/pow code comes from.

In hindsight, it would've been simpler to base it on the AJAX viewer slider instead. I'll give your code a try.

**Comment by Crispin-at-Linknode** [comment]
Hindsight, marvelous!  I'd be happy if the log scale was dumped completely and it became a linear slider.

**Comment by jumpinjackie** [comment]
I tried your code, and the results weren't really any different for non-tiled maps, so the actual problem is just with tiled maps. So in this case we just crunch the closest finite scale index and calculate the relative position of the slider and how many "notches" up or down it needs to be at.

Now the slider should display more realistically, especially in regards to tiled maps.

**Comment by Crispin-at-Linknode** [comment]
Thanks, it’s all looking MUCH better, I added another comment on #85

https://github.com/jumpinjackie/mapguide-react-layout/issues/85

Crispin
